### ISSUE TITLE
license for this repository

### ISSUE THREAD

**Issue by nisshan-x** [mayataka/mini_pupper_trajopt#1]
Hi.

What is the license for this repository?
I am considering publicly distributing software that has been created by quoting or modifying your software.

Thanks.

**Comment by mayataka** [comment]
@nisshan-x
Thank you for being interested in this repository.
I have added Apache-2.0 License, so feel free to use and re-distributing this software.

**Comment by nisshan-x** [comment]
Ok. Thank you.
